### ISSUE TITLE
[Question]: Unclear on versioning + plans for extended tool kit. [Answered]

### ISSUE THREAD

**Issue by MGRussell** [Krypton-Suite-Legacy/Krypton-NET-5.470#244]
I'm unclear on the purpose of the large number of independent repos for minor version differences. Are all changes being propagated to each repository or is there a primary repo?

Similarly the issue is even more unclear on the extended toolkit repos. It seems that the 5.48 extended toolit nuget package has been marked as deprecated (and indeed has not been updated in some time), yet the 5.47 extended line is being updated?

Krypton is great and it seems you've done a phenomenal job of solidifying and expanding it, but the project layout is not the most clear.

**Comment by Wagnerp** [comment]
Hi @MGRussell 

Thanks for the question, the major version `5` is named so as it is the only way to publish to NuGet without issues. `4xx` denotes which framework it's built for i.e `480` is built for .NET Framework 4.8. The 'old' 5.480 extended toolkit nuget package has been marked as deprecated in favour of a modular design, see [this](https://github.com/Wagnerp/Krypton-NET-Version-Dashboard/blob/master/Documents/Modules/Extended/Krypton-Toolkit-Suite-Extended-5480-Modules.md) for details.

It does take some time upgrading the packages, hence the reason for the delay. However as of 2020, the main development will come from 5.480 builds.

**Comment by MGRussell** [comment]
Ah! Ok. The fact that the depreciation was in favor of the modular design was quite unclear, even moreso since previous versions have not yet been marked as deprecated. Is there any reason for maintaining a build for each minor framework update? In other words, would an enduser gain any tangible benefit from running, for instance, 5.472 over this 5.470 version?

In any case, thanks for the quick response. I will leave this issue open though it's been resolved (additional questions I asked here notwithstanding) since I suspect I may not be the only one with some degree of confusing on the packaging/versioning criteria. Of course feel free to close it if you find it cluttering.

**Comment by Wagnerp** [comment]
NuGet is quite odd in that it won't allow users to install later versions on older frameworks. It's really there to ensure that there will be no issues on the user/developer side if you are targeting a specific framework. Plus some specific features in the extended toolkit are removed from 461 and lower due to newer APIs.

**Comment by Smurf-IV** [comment]
@Wagnerp Can the explanations given here be summarised and placed onto each repo's readme, and also in the "Overall Page" ?
And - if possible - in the nuGet description as well ?

**Comment by Wagnerp** [comment]
Hi @Smurf-IV 

Yes sure, I think that I've already put the .NET versions in the NuGet descriptions.

**Comment by Wagnerp** [comment]
Hi @MGRussell 

After a bit of thinking, we have decided to make a brand new package(s) `5.490.xxxx` that will encapsulate **all** supported .NET versions.
