### ISSUE TITLE
[BUG] Control and buttonspec with tooltips both appear at same time

### ISSUE THREAD

**Issue by Cocotteseb** [Krypton-Suite-Legacy/Krypton-NET-5.470#262]
Let's have for example a KryptonTextBox with a tooltip. On this Textbox we add a buttonspec which has a tooltip 
The tooltip of the textbox (from VisualContainerControlBase) appears alone, that's correct. 
The tooltip of the buttonspec appears along with the tooltip of the textbox : that's not intended and not correct. 
![image](https://user-images.githubusercontent.com/5160288/81474039-46e21400-9203-11ea-9628-b10dcf931d82.png)

![image](https://user-images.githubusercontent.com/5160288/81474058-53666c80-9203-11ea-9546-b6fd6ebc6b9e.png)

![image](https://user-images.githubusercontent.com/5160288/81474069-5eb99800-9203-11ea-9b41-d76e177a34be.png)

Related to feature : https://github.com/Krypton-Suite-Legacy/Krypton-NET-5.470/issues/85

I have no idea how to correct this. Can someone helps ?
Thanks

**Comment by Smurf-IV** [comment]
I can see pro's and con's for this.
The problemd, is that for every control that allows to have "ButtonExtra's" they handle the tooltips themselves (No base class code!).
So do "we" want introduce 
1) Base class code for extra (Best, but the greatest impact)
2) Have some magic in **every** tooltip extra handler to determine if the parent tooltip should be "closed"
3) Have an option to combine with 2 above?

**Comment by Smurf-IV** [comment]
Adding new `AllowButtonSpecTooltipPriority`
- If the parent Item has tooltips, and the button spec has tooltips, then the default is show both when hovering over the button spec. This can be disabled by setting `AllowButtonSpecTooltipPriority` to `true`, so that only 1 tooltip is displayed when hovering over any part of the control.

**Comment by Wagnerp** [comment]
Hi @Cocotteseb 

I've merged @Smurf-IV fixes into v5.500, and will be published in build 2006 along with other fixes.

**Comment by Cocotteseb** [comment]
Wow, that was quick ! Thanks @Smurf-IV for the reactivity. :)
That's an interesting solution indeed! Thanks @Wagnerp, I've made the modification in my own repository too (give full credits to the author with a backlink to this thread)

It does work perfectly when you are "already" in the control.
A little less when you are outside the control and then come "directly" on the buttonspec.
Here is an example : ![bandicam 2020-05-13 22-10-29-385](https://user-images.githubusercontent.com/5160288/81860364-f225fc80-9566-11ea-9b2b-1fbdbfbcdc02.gif)

The tooltip is displayed in the ToolTipManager on the MouseEnter event. Maybe using the MouseMove event and waiting for a small distance before activating the tooltip could be a way to overcome the above drawback ?
What do you think ?
